
'use server';
/**
 * @fileOverview A flow to test the core text generation functionality.
 * This is a minimal test to see if we can connect to a Gemini model.
 *
 * - testTextGeneration - A function that calls the text generation model.
 * - TestTextGenerationOutput - The return type.
 */
import { ai } from '@/ai/genkit';
import { genkit } from 'genkit';
import { googleAI, gemini15Flash } from '@genkit-ai/googleai';
import * as admin from 'firebase-admin';
import { z } from 'genkit';

const TestTextGenerationOutputSchema = z.object({
  success: z.boolean().describe('Indicates if the generation was successful.'),
  error: z.string().optional().describe('An error message if the test failed.'),
  generatedText: z.string().optional().describe('The text generated by the model.'),
});
export type TestTextGenerationOutput = z.infer<typeof TestTextGenerationOutputSchema>;

export async function testTextGeneration(): Promise<TestTextGenerationOutput> {
  return testTextGenerationFlow();
}

const testTextGenerationFlow = ai.defineFlow(
  {
    name: 'testTextGenerationFlow',
    inputSchema: z.void(),
    outputSchema: TestTextGenerationOutputSchema,
  },
  async () => {
    try {
      // --- Start of API Key logic ---
      if (admin.apps.length === 0) {
        admin.initializeApp();
      }
      const db = admin.firestore();
      const FIRESTORE_KEYS_PATH = "configurations/api_keys_config";
      const docRef = db.doc(FIRESTORE_KEYS_PATH);
      const docSnap = await docRef.get();
      const apiKey = docSnap.exists() ? docSnap.data()?.googleAiApiKey : null;

      let chatAi = ai; // Default instance
      if (apiKey && typeof apiKey === 'string' && apiKey.trim() !== '') {
          console.log('[testTextGenerationFlow] Using Google AI API Key from Firestore.');
          chatAi = genkit({
              plugins: [googleAI({ apiKey: apiKey.trim() })],
          });
      } else {
          console.log('[testTextGenerationFlow] Using default Genkit instance (ADC).');
      }
      // --- End of API Key logic ---
      
      const result = await chatAi.generate({
        model: gemini15Flash,
        prompt: 'Tell me a one-sentence joke.',
      });

      const text = result.text;

      if (text) {
        return {
          success: true,
          generatedText: text,
        };
      } else {
        const fullResponse = JSON.stringify(result, null, 2);
        return {
          success: false,
          error: `The text generation service returned a successful but empty response. This may indicate a problem with the Vertex AI API configuration or project billing. Full response: ${fullResponse}`,
        };
      }
    } catch (e: any) {
      console.error('[testTextGenerationFlow] Full exception object caught:', JSON.stringify(e, Object.getOwnPropertyNames(e), 2));
      const errorMessage = `The test failed with an unexpected exception: ${e.message || 'Unknown error'}. This often points to an issue with authentication, API enablement, or billing in your Google Cloud project. Full details: ${JSON.stringify(e, Object.getOwnPropertyNames(e), 2)}`;
      return {
          success: false,
          error: errorMessage,
      };
    }
  }
);
